routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {

        Route::resource('user', 'User\UserController')->except(['show', 'delete']);
        Route::resource('transaction', 'Transaction\TransactionController')->except(['edit', 'delete']);
    });
});

app/Models/Transaction/Transaction.php
<?php
/**
 * Created for transactions.
 * User: Sergio Martin Marquina
 * Email: smarquina@zenos.es
 * Date: 09/04/2019
 * Time: 15:46
 */

namespace App\Models\Transaction;


use App\Models\BaseModel;
use App\Models\User\User;

/**
 * App\Models\Transaction\Transaction
 *
 * @property int $id
 * @property int $user_from
 * @property int $user_to
 * @property string $subject
 * @property string|null $comment
 * @property mixed $quantity
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User\User $userFrom
 * @property-read \App\Models\User\User $userTo
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction whereComment($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction whereQuantity($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction whereSubject($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction whereUserFrom($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Transaction\Transaction whereUserTo($value)
 * @mixin \Eloquent
 */
class Transaction extends BaseModel
{
    protected $table = 'transaction';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'subject', 'quantity', 'comment', 'user_from', 'user_to',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [

    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'user_from' => 'integer',
        'user_to'   => 'integer',
        'subject'   => 'string',
        'quantity'  => 'numeric',
        'comment'   => 'string',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function userFrom()
    {
        return $this->belongsTo(User::class, 'user_from');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function userTo()
    {
        return $this->belongsTo(User::class, 'user_to');
    }
}

app/Http/Controllers/Admin/Transaction/TransactionController.php
<?php
/**
 * Created for transactions.
 * User: Sergio Martin Marquina
 * Email: smarquina@zenos.es
 * Date: 15/04/2019
 * Time: 10:17
 */

namespace App\Http\Controllers\Admin\Transaction;


use App\Http\Controllers\Controller;
use App\Models\Transaction\Transaction;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class TransactionController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $query = Transaction::select(["transaction.id",
                                          "userFrom.name as user_from_name",
                                          "userTo.name as user_to_name",
                                          'transaction.quantity',
                                          'transaction.subject',
                                         ])
                                ->leftJoin('users as userFrom', 'transaction.user_from', 'userFrom.id')
                                ->leftJoin('users as userTo', 'transaction.user_to', 'userTo.id')
                                ->orderBy("id", "DESC")
                                ->get();

            return DataTables::collection($query)
                             ->setRowId('id')
                             ->make(true);

        } else return view('transaction.list');
    }

    public function show(Transaction $transaction)
    {
        return view('transaction.list', compact('transaction'));
    }
}

app/Http/Controllers/Api/Transaction/TransactionController.php
<?php
/**
 * Created for transactions.
 * User: Sergio Martin Marquina
 * Email: smarquina@zenos.es
 * Date: 15/04/2019
 * Time: 10:54
 */

namespace App\Http\Controllers\Api\Transaction;


use App\Emuns\HttpErrors;
use App\Http\Controllers\Api\ApiBaseController;
use App\Http\Managers\Transaction\TransactionManager;
use App\Http\Requests\Transaction\TransactionRequest;
use App\Http\Resources\Transacion\TransactionResource;
use App\Models\Transaction\Transaction;
use App\Models\User\User;
use App\Response\ApiResponse;
use Dingo\Api\Exception\ResourceException;
use Dingo\Api\Exception\ValidationHttpException;

/**
 * Class TransactionController
 * @package App\Http\Controllers\Api\Transaction
 */
class TransactionController extends ApiBaseController
{
    /**
     * @param TransactionRequest $request
     * @return TransactionResource|\Illuminate\Http\JsonResponse
     *
     * @throws \Exception
     * @OA\Post(
     *   path="/api/transaction/create",
     *   summary="Store new transaction",
     *   tags={"transaction"},
     *   operationId="createTransaction",
     *   @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(
     *                 @OA\Property(
     *                     property="user_to",
     *                     type="required|exists:users,id",
     *                 ),
     *                 @OA\Property(
     *                     property="quantity",
     *                     type="required|numeric|min:0"
     *                 ),
     *                 @OA\Property(
     *                     property="subject",
     *                     type="required|string|max:255"
     *                 ),
     *                 @OA\Property(
     *                     property="comment",
     *                     type="nullable|string|max:1000"
     *                 ),
     *             )
     *         ),
     *   ),
     *   @OA\Response(
     *     response=200,
     *     description="Transaction data",
     *     @OA\JsonContent(type="array",
     *       @OA\Items(ref="#/components/schemas/Transaction"),
     *     ),
     *   ),
     *   @OA\Response(
     *     response=422,
     *     description="Reqest validarion errors",
     *     @OA\JsonContent(type="object",
     *      @OA\Items(title="message", description="message", type="string"),
     *      @OA\Items(title="errors", description="array with errors", type="array"),
     *      @OA\Items(title="status_code", description="error code", type="integer"),
     *     ),
     *   ),
     *   @OA\Response(
     *     response=550,
     *     description="Cant store data",
     *     ),
     *   ),
     * )
     */
    public function createTransaction(TransactionRequest $request)
    {
        try {
            \DB::beginTransaction();
            /** @var User $user */
            $user = \Auth::user();
            if ($user->amount >= $request->input('quantity')) {

                $transaction = (new TransactionManager())->makeTransaction($user, $request->all());
                \DB::commit();
                return new TransactionResource($transaction);
            } else {
                throw new ValidationHttpException([
                                                      'quantity' => trans('general.transaction.not_enough'),
                                                  ]);
            }
        } catch (ValidationHttpException $exception) {
            throw new ResourceException('422 Unprocessable Entity', $exception->getErrors(), null, [],
                                        HttpErrors::CANT_COMPLETE_VALIDATION);
        } catch (ResourceException $exception) {
            \DB::rollBack();
            \Log::error($exception);
            return ApiResponse::responseWithError(HttpErrors::CANT_COMPLETE_REQUEST, $exception->getMessage(), $exception->getErrors());
        } catch (\Exception $exception) {
            \DB::rollBack();

            \Log::error($exception);
            $msg = config('app.debug') ? $exception->getMessage() : trans('general.transaction.save_error');
            return ApiResponse::responseWithError(HttpErrors::CANT_COMPLETE_REQUEST, $msg);
        }
    }

    /**
     * Get sent transactions.
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Resources\Json\AnonymousResourceCollection
     *
     * @OA\Get(
     *   path="/api/transaction/sent",
     *   summary="Sent transactions",
     *   tags={"transaction"},
     *   operationId="sentTransactions",
     *
     *   @OA\Response(
     *     response=200,
     *     description="A list of my transactions",
     *     @OA\JsonContent(type="array",
     *       @OA\Items(ref="#/components/schemas/Transaction")
     *   ),
     *  )
     * )
     *
     */
    public function sentTransactions()
    {
        try {
            $transactions = Transaction::whereUserFrom(\Auth::id())
                                       ->get();

            return TransactionResource::collection($transactions);
        } catch (\Exception $exception) {
            \Log::error($exception);
            $msg = config('app.debug') ? $exception->getMessage() : trans('general.model.find.error');
            return ApiResponse::responseWithError(HttpErrors::CANT_COMPLETE_REQUEST, $msg);
        }
    }

    /**
     * Get income transactions.
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Resources\Json\AnonymousResourceCollection
     *
     * @OA\Get(
     *   path="/api/transaction/income",
     *   summary="Income transactions",
     *   tags={"transaction"},
     *   operationId="incomeTransactions",
     *
     *   @OA\Response(
     *     response=200,
     *     description="A list of my transactions",
     *     @OA\JsonContent(type="array",
     *       @OA\Items(ref="#/components/schemas/Transaction")
     *   ),
     *  )
     * )
     *
     */
    public function incomeTransactions()
    {
        try {
            $transactions = Transaction::whereUserTo(\Auth::id())
                                       ->get();

            return TransactionResource::collection($transactions);
        } catch (\Exception $exception) {
            \Log::error($exception);
            $msg = config('app.debug') ? $exception->getMessage() : trans('general.model.find.error');
            return ApiResponse::responseWithError(HttpErrors::CANT_COMPLETE_REQUEST, $msg);
        }
    }
}

resources/views/transaction/list.blade.php
@extends('adminlte::page')

@section('title', 'transactions transacciones')

@section('content_header')
    <h1>Transacciones</h1>
@stop

@section('content')
    <section class="content">

        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Listado de transacciones</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div class="dataTables_wrapper form-inline no-footer">

                    <table id="tabla"
                           class="table table-responsive table-hover table-striped filter-head dataTable no-footer">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre Pagador</th>
                            <th>Nombre Receptor</th>
                            <th>Cantidad</th>
                            <th>Concepto</th>
{{--                            <th>Acciones</th>--}}
                        </tr>
                        </thead>
                    </table>
                </div>

            </div><!-- /.box-body -->
            <div class="box-footer text-center">

            </div><!-- /.box-footer -->
        </div><!-- /.box -->

    </section>
@stop

@section('js')
    <script type="text/javascript" src="//cdn.datatables.net/v/bs/dt-1.10.13/datatables.min.js"></script>

    <script type="text/javascript">

        jQuery(document).ready(function () {
            // Ordenar la tabla de forma inversa por ID
            jQuery('#tabla').DataTable({
                // set the initial value
                ordering: true,
                info: true,
                autoWidth: false,

                bPaginate: true,
                searching: true,
                processing: true,
                serverSide: true,
                ajax: '{{route('admin.transaction.index')}}',
                columns: [
                    {data: "id", name: "id", className: "text-center"},
                    {data: "user_from_name", name: "user_from_name", className: "text-center"},
                    {data: "user_to_name", name: "user_to_name", className: "text-center"},
                    {data: "quantity", name: "quantity", className: "text-center"},
                    {data: "subject", name: "subject", className: "text-center"},
                    // {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json'
                },
                initComplete: function () {
                    $('#tabla_filter').hide();
                    $('.filter-head thead th').each(function () {
                        var title = $('.filter-head thead th').eq($(this).index()).text();
                        if (title != 'Acciones') {
                            $(this).append('<br><input type="text" onclick="stopPropagation(event);" class="form-control input-sm text-center" placeholder="Filtro de ' + title + '" />');
                        }
                    });
                    var table = $('.filter-head').DataTable();
                    $(".filter-head thead input").on('keyup change', function () {
                        table.column($(this).parent().index() + ':visible').search(this.value).draw();
                    });
                }
            });
        });

    </script>
@stop