routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {

        Route::resource('user', 'User\UserController')->except(['show', 'delete']);
        Route::resource('transaction', 'Transaction\TransactionController')->except(['edit', 'delete']);
    });
});

app/Models/User/User.php
<?php
/**
 * Created for transactions.
 * User: Sergio Martin Marquina
 * Email: smarquina@zenos.es
 * Date: 09/04/2019
 * Time: 14:49
 */

namespace App\Models\User;


use App\Models\BaseModel;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;

/**
 * App\Models\User\User
 *
 * @property int                                                                                                            $id
 * @property string                                                                                                         $name
 * @property string                                                                                                         $email
 * @property \Illuminate\Support\Carbon|null                                                                                $email_verified_at
 * @property string                                                                                                         $password
 * @property string|null                                                                                                    $remember_token
 * @property \Illuminate\Support\Carbon|null                                                                                $created_at
 * @property \Illuminate\Support\Carbon|null                                                                                $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property float $amount
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User\User whereAmount($value)
 */
class User extends BaseModel implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract, JWTSubject
{
    use Notifiable, Authenticatable, Authorizable, CanResetPassword;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/Admin/User/UserController.php
<?php
/**
 * Created for transactions.
 * User: Sergio Martin Marquina
 * Email: smarquina@zenos.es
 * Date: 15/04/2019
 * Time: 2:40
 */

namespace App\Http\Controllers\Admin\User;


use App\Http\Controllers\Controller;
use App\Models\User\User;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $query = User::select(["id",
                                   "name",
                                   "email",
                                   "amount",
                                  ])
                         ->orderBy("id", "DESC")
                         ->get();

            return DataTables::collection($query)
                             ->setRowId('id')
                             ->make(true);

        } else return view('user.list');
    }
}

resources/views/user/list.blade.php
@extends('adminlte::page')

@section('title', 'Usuarios')

@section('content_header')
    <h1>Usuarios</h1>
@stop

@section('content')
    <section class="content">

        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Listado de usuarios</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">

                {{--                @include('admin.layout.messages')--}}
                <div class="dataTables_wrapper form-inline no-footer">

                    <table id="tabla"
                           class="table table-responsive table-hover table-striped filter-head dataTable no-footer">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th>Disponible</th>
{{--                            <th>Acciones</th>--}}
                        </tr>
                        </thead>
                    </table>
                </div>

            </div><!-- /.box-body -->
            <div class="box-footer text-center">

            </div><!-- /.box-footer -->
        </div><!-- /.box -->

    </section>
@stop

@section('js')
    <script type="text/javascript" src="//cdn.datatables.net/v/bs/dt-1.10.13/datatables.min.js"></script>

    <script type="text/javascript">

        jQuery(document).ready(function () {
            // Ordenar la tabla de forma inversa por ID
            jQuery('#tabla').DataTable({
                // set the initial value
                ordering: true,
                info: true,
                autoWidth: false,

                bPaginate: true,
                searching: true,
                processing: true,
                serverSide: true,
                ajax: '{{route('admin.user.index')}}',
                columns: [
                    {data: "id", name: "id", className: "text-center"},
                    {data: "name", name: "name", className: "text-center"},
                    {data: "email", name: "email", className: "text-center"},
                    {data: "amount", name: "amount", className: "text-center"},
                    // {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json'
                },
                initComplete: function () {
                    $('#tabla_filter').hide();
                    $('.filter-head thead th').each(function () {
                        var title = $('.filter-head thead th').eq($(this).index()).text();
                        if (title != 'Acciones') {
                            $(this).append('<br><input type="text" onclick="stopPropagation(event);" class="form-control input-sm text-center" placeholder="Filtro de ' + title + '" />');
                        }
                    });
                    var table = $('.filter-head').DataTable();
                    $(".filter-head thead input").on('keyup change', function () {
                        table.column($(this).parent().index() + ':visible').search(this.value).draw();
                    });
                }
            });
        });

    </script>
@stop